/* Generated by Pyrex 0.9.8.4 on Wed Mar 11 19:40:51 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from code */


/* Declarations from implementation of code */


static char __pyx_k1[] = "Yi";
static char __pyx_k2[] = "import topology; import neighborhood; import agent";
static char __pyx_k3[] = "Yc";
static char __pyx_k4[] = "corporality = neighborhood.VonNeumannNeighborhood";
static char __pyx_k5[] = "Ys";
static char __pyx_k6[] = "sensoriality = neighborhood.VonNeumannNeighborhood";
static char __pyx_k7[] = "Cb";
static char __pyx_k8[] = "def birth(earth, code, prana, mana, address):";
static char __pyx_k9[] = "Cd";
static char __pyx_k10[] = "  myself = agent.Agent_2D(code,corporality(earth.returnTopology()),sensoriality(earth.returnTopology()),prana,mana,address)";
static char __pyx_k11[] = "Cr";
static char __pyx_k12[] = "  return myself";
static char __pyx_k13[] = "Tl";
static char __pyx_k14[] = "def live(creature, numen, index):";
static char __pyx_k15[] = "Te";
static char __pyx_k16[] = "  pass # creature.eatMana()";
static char __pyx_k17[] = "Tr";
static char __pyx_k18[] = "  if creature.tellPrana() > 11: reproduce(creature, numen, index)";
static char __pyx_k19[] = "Tp";
static char __pyx_k20[] = "  pass";
static char __pyx_k21[] = "Rd";
static char __pyx_k22[] = "def reproduce(creature, numen, index):";
static char __pyx_k23[] = "Rp";
static char __pyx_k24[] = "  numen[index-1][4][\"prayer\"]=\"GRANT_CHILD\"";
static char __pyx_k25[] = "Rc";
static char __pyx_k26[] = "  numen[index-1][4][\"code\"]=creature.tellCode()";
static char __pyx_k27[] = "Rl";
static char __pyx_k28[] = "  creature.losePrana(10)";
static char __pyx_k29[] = "tabula";
static char __pyx_k30[] = "ai";
static char __pyx_k31[] = "import topolog; import neighborhood; import rule; import operator; import automaton; import agent; import genome; import random";
static char __pyx_k32[] = "at";
static char __pyx_k33[] = "topos = topology.ToroidTopology((90,40),0)";
static char __pyx_k34[] = "ap";
static char __pyx_k35[] = "change = rule.ReductionRule(ball,(operator.xor,0))";
static char __pyx_k36[] = "au";
static char __pyx_k37[] = "robot = automaton.SynchronousAutomaton_2D(change)";
static char __pyx_k38[] = "ic";
static char __pyx_k39[] = "class corpus:";
static char __pyx_k40[] = "ii";
static char __pyx_k41[] = "  ";
static char __pyx_k42[] = "id";
static char __pyx_k43[] = "def __init__(self, topos):";
static char __pyx_k44[] = "it";
static char __pyx_k45[] = "  self.topos = topos";
static char __pyx_k46[] = "an";
static char __pyx_k47[] = "  self.ball = neighborhood.VonNeumannNeighborhood(topos)";
static char __pyx_k48[] = "aw";
static char __pyx_k49[] = "def wander(agent):";
static char __pyx_k50[] = "ar";
static char __pyx_k51[] = "  direction = random.randint(0,4)";
static char __pyx_k52[] = "ac";
static char __pyx_k53[] = "  agent.changeFacing(direction)";
static char __pyx_k54[] = "aa";
static char __pyx_k55[] = "  agent.advance()";
static char __pyx_k56[] = "ae";
static char __pyx_k57[] = "  agent.eatMana()";
static char __pyx_k58[] = "zd";
static char __pyx_k59[] = "def beBorn(topos):";
static char __pyx_k60[] = "zn";
static char __pyx_k61[] = "  ball = neighborhood.VonNeumannNeighborhood(topos)";
static char __pyx_k62[] = "zm";
static char __pyx_k63[] = "  myself = agent.Agent_2D(genome.Genome([],{},2),ball,ball,50,1,(30,8))";
static char __pyx_k64[] = "za";
static char __pyx_k65[] = "pd";
static char __pyx_k66[] = "def __print__():";
static char __pyx_k67[] = "pp";
static char __pyx_k68[] = "  return myself.tellAddress()";
static char __pyx_k69[] = "tabula_antica";

static PyObject *__pyx_n_Cb;
static PyObject *__pyx_n_Cd;
static PyObject *__pyx_n_Cr;
static PyObject *__pyx_n_Rc;
static PyObject *__pyx_n_Rd;
static PyObject *__pyx_n_Rl;
static PyObject *__pyx_n_Rp;
static PyObject *__pyx_n_Te;
static PyObject *__pyx_n_Tl;
static PyObject *__pyx_n_Tp;
static PyObject *__pyx_n_Tr;
static PyObject *__pyx_n_Yc;
static PyObject *__pyx_n_Yi;
static PyObject *__pyx_n_Ys;
static PyObject *__pyx_n_aa;
static PyObject *__pyx_n_ac;
static PyObject *__pyx_n_ae;
static PyObject *__pyx_n_ai;
static PyObject *__pyx_n_an;
static PyObject *__pyx_n_ap;
static PyObject *__pyx_n_ar;
static PyObject *__pyx_n_at;
static PyObject *__pyx_n_au;
static PyObject *__pyx_n_aw;
static PyObject *__pyx_n_ic;
static PyObject *__pyx_n_id;
static PyObject *__pyx_n_ii;
static PyObject *__pyx_n_it;
static PyObject *__pyx_n_pd;
static PyObject *__pyx_n_pp;
static PyObject *__pyx_n_tabula;
static PyObject *__pyx_n_tabula_antica;
static PyObject *__pyx_n_za;
static PyObject *__pyx_n_zd;
static PyObject *__pyx_n_zm;
static PyObject *__pyx_n_zn;

static PyObject *__pyx_k2p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k8p;
static PyObject *__pyx_k10p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k14p;
static PyObject *__pyx_k16p;
static PyObject *__pyx_k18p;
static PyObject *__pyx_k20p;
static PyObject *__pyx_k22p;
static PyObject *__pyx_k24p;
static PyObject *__pyx_k26p;
static PyObject *__pyx_k28p;
static PyObject *__pyx_k31p;
static PyObject *__pyx_k33p;
static PyObject *__pyx_k35p;
static PyObject *__pyx_k37p;
static PyObject *__pyx_k39p;
static PyObject *__pyx_k41p;
static PyObject *__pyx_k43p;
static PyObject *__pyx_k45p;
static PyObject *__pyx_k47p;
static PyObject *__pyx_k49p;
static PyObject *__pyx_k51p;
static PyObject *__pyx_k53p;
static PyObject *__pyx_k55p;
static PyObject *__pyx_k57p;
static PyObject *__pyx_k59p;
static PyObject *__pyx_k61p;
static PyObject *__pyx_k63p;
static PyObject *__pyx_k66p;
static PyObject *__pyx_k68p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_Cb, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_Cd, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_Cr, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_Rc, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_Rd, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_Rl, 1, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_n_Rp, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_Te, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_Tl, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_Tp, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_Tr, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_Yc, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_Yi, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_Ys, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_aa, 1, __pyx_k54, sizeof(__pyx_k54)},
  {&__pyx_n_ac, 1, __pyx_k52, sizeof(__pyx_k52)},
  {&__pyx_n_ae, 1, __pyx_k56, sizeof(__pyx_k56)},
  {&__pyx_n_ai, 1, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_n_an, 1, __pyx_k46, sizeof(__pyx_k46)},
  {&__pyx_n_ap, 1, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_n_ar, 1, __pyx_k50, sizeof(__pyx_k50)},
  {&__pyx_n_at, 1, __pyx_k32, sizeof(__pyx_k32)},
  {&__pyx_n_au, 1, __pyx_k36, sizeof(__pyx_k36)},
  {&__pyx_n_aw, 1, __pyx_k48, sizeof(__pyx_k48)},
  {&__pyx_n_ic, 1, __pyx_k38, sizeof(__pyx_k38)},
  {&__pyx_n_id, 1, __pyx_k42, sizeof(__pyx_k42)},
  {&__pyx_n_ii, 1, __pyx_k40, sizeof(__pyx_k40)},
  {&__pyx_n_it, 1, __pyx_k44, sizeof(__pyx_k44)},
  {&__pyx_n_pd, 1, __pyx_k65, sizeof(__pyx_k65)},
  {&__pyx_n_pp, 1, __pyx_k67, sizeof(__pyx_k67)},
  {&__pyx_n_tabula, 1, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_n_tabula_antica, 1, __pyx_k69, sizeof(__pyx_k69)},
  {&__pyx_n_za, 1, __pyx_k64, sizeof(__pyx_k64)},
  {&__pyx_n_zd, 1, __pyx_k58, sizeof(__pyx_k58)},
  {&__pyx_n_zm, 1, __pyx_k62, sizeof(__pyx_k62)},
  {&__pyx_n_zn, 1, __pyx_k60, sizeof(__pyx_k60)},
  {&__pyx_k2p, 0, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k10p, 0, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k14p, 0, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k16p, 0, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_k18p, 0, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k20p, 0, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k22p, 0, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_k24p, 0, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_k26p, 0, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_k28p, 0, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_k31p, 0, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_k33p, 0, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_k35p, 0, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_k37p, 0, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_k39p, 0, __pyx_k39, sizeof(__pyx_k39)},
  {&__pyx_k41p, 0, __pyx_k41, sizeof(__pyx_k41)},
  {&__pyx_k43p, 0, __pyx_k43, sizeof(__pyx_k43)},
  {&__pyx_k45p, 0, __pyx_k45, sizeof(__pyx_k45)},
  {&__pyx_k47p, 0, __pyx_k47, sizeof(__pyx_k47)},
  {&__pyx_k49p, 0, __pyx_k49, sizeof(__pyx_k49)},
  {&__pyx_k51p, 0, __pyx_k51, sizeof(__pyx_k51)},
  {&__pyx_k53p, 0, __pyx_k53, sizeof(__pyx_k53)},
  {&__pyx_k55p, 0, __pyx_k55, sizeof(__pyx_k55)},
  {&__pyx_k57p, 0, __pyx_k57, sizeof(__pyx_k57)},
  {&__pyx_k59p, 0, __pyx_k59, sizeof(__pyx_k59)},
  {&__pyx_k61p, 0, __pyx_k61, sizeof(__pyx_k61)},
  {&__pyx_k63p, 0, __pyx_k63, sizeof(__pyx_k63)},
  {&__pyx_k66p, 0, __pyx_k66, sizeof(__pyx_k66)},
  {&__pyx_k68p, 0, __pyx_k68, sizeof(__pyx_k68)},
  {0, 0, 0, 0}
};



/* Implementation of code */

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initcode(void); /*proto*/
PyMODINIT_FUNC initcode(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("code", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "/home/ernesto/Documents/Ouroborus/ouroborus/birdcage/code.pyx":1 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Yi, __pyx_k2p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Yc, __pyx_k4p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Ys, __pyx_k6p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Cb, __pyx_k8p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Cd, __pyx_k10p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Cr, __pyx_k12p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Tl, __pyx_k14p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Te, __pyx_k16p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Tr, __pyx_k18p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Tp, __pyx_k20p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Rd, __pyx_k22p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Rp, __pyx_k24p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Rc, __pyx_k26p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_Rl, __pyx_k28p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_tabula, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ernesto/Documents/Ouroborus/ouroborus/birdcage/code.pyx":17 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ai, __pyx_k31p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_at, __pyx_k33p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ap, __pyx_k35p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_au, __pyx_k37p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ic, __pyx_k39p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ii, __pyx_k41p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_id, __pyx_k43p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_it, __pyx_k45p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_an, __pyx_k47p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_aw, __pyx_k49p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ar, __pyx_k51p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ac, __pyx_k53p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_aa, __pyx_k55p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_ae, __pyx_k57p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_zd, __pyx_k59p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_zn, __pyx_k61p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_zm, __pyx_k63p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_za, __pyx_k12p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_pd, __pyx_k66p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_pp, __pyx_k68p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_tabula_antica, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("code");
}

static char *__pyx_filenames[] = {
  "code.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
